# INTRODUCTION {#sec:introduction}

The Yukon River is one of the largest and most isolated river systems in North America. It drains over 850,000 square kilometers from its headwaters in northern British Columbia through the Yukon Territory in Canada and Alaska in United States, before emptying into the Bering Sea [@brabets2000environmental]. It is also one of the world’s largest salmon producing river basins with millions of salmon entering the river in most years [@JTC2025Report]. Among the Pacific salmon species that return to the Yukon River are Chinook salmon (*Oncorhynchus tshawytscha*) which spawn throughout the basin with nearly half returning to one of hundreds of Canadian streams to spawn each year [@JTC2025Report; @brown2017].  

Yukon River Chinook salmon have supported subsistence and First Nations fisheries and cultural practices for millennia. In more recent years they have also supported commercial and recreational fisheries. In 2001, Canada and the United States finalized the Yukon River Salmon Agreement, a chapter of the Pacific Salmon Treaty (1985), where a spawning escapement goal for mainstem Canadian-origin Yukon River Chinook salmon was set at 33,000 to 43,000 and joint assessment projects were initiated. Prior to 2002, annual harvests of Chinook salmon in the Yukon River averaged 150,000 fish, but dropped to near 50,000 in the early 2000s as a result of low return sizes and fishery closures. An updated "interim management" escapement goal (IMEG) of 42,500 to 55,000 Chinook salmon was established in 2010. Aggregate returns of Canadian-origin Yukon River Chinook salmon have declined in the decades since culminating in five of the lowest returns on record in 2020–2024 [@JTC2025Report]. These declines have placed immense hardship on subsistence users and First Nations who depend on Yukon River Chinook salmon for food, social and cultural uses, and there have been simultaneous declines in average female reproductive potential [due to declines in size and age, @ohlberger_reproductive_2020] and changing freshwater and marine conditions experienced throughout the Chinook salmon life cycle [@feddern2024; @murdoch2024; @howard2023]. In 2024, an agreement was reached between the Alaska Department of Fish and Game (ADF&G) and Fisheries and Oceans Canada (DFO) which included fishery closures throughout the drainage and established a rebuilding target of 71,000 Chinook salmon to pass the U.S.--Canada international border. 

In addition to the provisions of the Yukon River Salmon Agreement, Yukon River Chinook salmon and Porcupine Chinook salmon have been proposed as a major fish stock under the Fish Stocks provisions of Canada’s recently amended *Fisheries Act*. The major fish stocks identification comes with a requirement to develop three reference points: a Limit Reference Point (LRP), a Upper Stock Reference (USR), and a Removal Reference (RR; Section \@ref(sec:status-trends)). These candidate reference points should be relevant to the scale at which assessment and management occurs, the types of information that are collected, how assessments are used to support decision making, and should be consistent with existing policies [e.g., Canada's Wild Salmon Policy,@holt2023guidelines]. The Fish Stocks provisions require that the Government of Canada use these reference points to “maintain major fish stocks at or above the level necessary to promote the sustainability of the stock, taking into account the biology of the fish and the environmental conditions affecting the stock” [@DFO1985Act]. A rebuilding plan is required per section 6.2 of the Fish Stocks provisions if the stock is assessed to be below its LRP. In support of these legislative requirements, the Fisheries Management sector of DFO requested science advice on stock status and the expected impacts of harvest and rebuilding actions on Canadian-origin Yukon River Chinook salmon. Throughout this document, salmon originating from the Canadian portion of the Yukon River basin will be referred to as Yukon River Chinook salmon for brevity.   

<!-- Under Canada’s Wild Salmon Policy [@WSP2005], Canadian Yukon River Chinook salmon belong to 12 conservation units (CUs) which are genetically and ecologically unique [@holtbyConservationUnitsPacific2007]. These 12 CUs represent 2 stock management units (SMU): Yukon River Chinook salmon and Porcupine Chinook salmon. Canadian-origin Yukon River Chinook salmon are genetically unique within the entire drainage, and sampling in the lower river provides in-season estimates of the Canadian component that enter the system. These data are used by fisheries managers in-season when determining appropriate management measures throughout the drainage. Since 1982, projects on the Yukon River have provided critical data on Chinook salmon passing the international border. From 1982–2004, a mark-recapture program utilizing fishwheels operated 15 river kilometers (rkm) upstream of the border and since 2005, an assessment site near Eagle, Alaska, 20 rkm downstream of the border has used sonars to estimate passage. Since 2023, a run reconstruction model [@JTC2025Report; @connors_estimates_2023] has been used which incorporates assessment data to provide a postseason estimate of border passage. Escapement of Canadian-origin Chinook salmon is determined by removing harvest estimated to have occurred upstream of the Eagle sonar assessment site, in both U.S. and Canada. Chinook salmon returning to the Canadian portion of the Porcupine River move into the Porcupine River at Fort Yukon, Alaska, downstream of the U.S. and Canada border, and downstream of the assessment site near Eagle, Alaska. Assessment of Canadian-origin Chinook salmon in the Porcupine River has occurred at a site near Old Crow, Yukon since 2014. The total escapement of all Canadian-origin Yukon River Chinook salmon would therefore need to include estimates from the assessment sites on the mainstem Yukon River near Eagle, Alaska and on the Porcupine River near Old Crow, Yukon. -->



## OBJECTIVES

The specific objectives of this research document are to:

1.  Describe current understanding of (a) major stock structure and distribution, (b) major stock, and component Conservation Units, status and trends, and (c) anthropogenic, ecosystem, and climate factors affecting Canadian-origin Yukon River Chinook salmon;

2.  Describe potential rebuilding and enhancement activities that could contribute to Canadian-origin Yukon River Chinook salmon rebuilding;

3.  Provide estimates of a Limit Reference Point and other candidate reference points (e.g., Upper Stock Reference and Removal Reference) for the Yukon Chinook Stock Management Unit (SMU);

4.  Provide quantitative estimates of the expected biological and fishery consequences of current and alternative harvest management measures (e.g., no fishing, interim aggregate escapement goal, rebuilding goal, exploitation rate caps based on Conservation Unit overfishing risk, etc.) that could contribute to Yukon Chinook SMU rebuilding;

5.  Propose exceptional circumstances or assessment triggers for Yukon Chinook SMU (e.g., circumstances or conditions that represent a substantial departure from those under which the advice in this assessment was developed); and

6.  Identify key knowledge gaps and areas requiring future work.
