# STOCK STRUCTURE, BIOLOGY, AND DISTRIBUTION {#sec:stock}

Under Canada’s Wild Salmon Policy [@WSP2005], Canadian-origin Yukon River Chinook salmon belong to 12 conservation units (CUs) which are genetically and ecologically unique [Table \@ref(tab:tab-cons-unit-smu), @holtbyConservationUnitsPacific2007; @holtby2011]. Conservation units were identified in 2007 and 2009 using genetics, life history characteristics (such as stream-type or ocean-type), and biogeographic zones of the near-shore and freshwater environments [@holtbyConservationUnitsPacific2007; @holtby2011; @wade2019]. The populations and delineation of each CU can be adjusted, deleted, or created if necessary after submission to and review by DFO's Salmon Data Unit [@wade2019]. The 12 CUs for Canadian-origin Yukon Chinook represent two stock management units (SMU): Yukon River Chinook salmon and Porcupine River Chinook salmon [@dfo2024yukonifmp]. Nine CUs are from watersheds draining into the mainstem of the Yukon River and three CUs from the Porcupine River. The Porcupine River SMU joins the Yukon River at Fort Yukon, Alaska, downstream of the U.S.--Canada border, and downstream of the assessment site near Eagle, Alaska which estimates Yukon Chinook SMU escapement. DFO manages these two SMUs separately due to differences in assessment projects, data availability, harvest decision rules, and fishery management objectives [@dfo2024yukonifmp]. However, under the Fish Stocks provisions, both SMUs are combined into one "major stock" under legislation. Much of the analysis herein applies to the Yukon Chinook SMU, and not the Porcupine SMU. 

Canadian-origin Yukon River Chinook salmon are genetically unique within the entire drainage basin, and sampling in the lower river, near the river mouth, provides in-season estimates of the Canadian component that enter the system. On average, the annual proportion of the total return of Chinook salmon to the Yukon River that are Canadian origin is 42% and has historically varied from 31%--54% [@JTC2025Report]. These Chinook salmon spawn in over 100 spawning locations throughout the Canadian portion of the watershed [Figure \@ref(fig:fig-map-spawn), @brown2017].

The Porcupine River basin, located in northern Yukon is comprised of three Chinook salmon CUs: Old Crow, Salmon Fork, and Porcupine (Figure \@ref(fig:fig-map-spawn)). Little data exists from Chinook salmon from the Salmon Fork CU, and spawning abundance is believed to be very low. The Porcupine CU is the most abundant of the SMU [@dfo2024yukonifmp]. Chinook salmon passage in the Porcupine River has been estimated using sonar since 2014 near the community of Old Crow, and estimates the combined abundances of the Porcupine and Old Crow CUs (Figure \@ref(fig:fig-map-assess)). The average annual estimate is 2,800 fish and the most recent estimate was 468 in 2024 [@JTC2025Report].

Further south, along the mainstem Yukon River within Canada, nine CUs form a single SMU which contains the majority of Canadian-origin Yukon Chinook salmon (Figure \@ref(fig:fig-map-spawn)).The nine CUs comprising the Yukon Chinook SMU are: Northern Yukon and tributaries (hereafter "Northern Yukon"), White and tributaries ("White"), Stewart, Middle Yukon River and tributaries ("Middle Yukon"), Pelly, Nordenskiold, Big Salmon, Upper Yukon River ("Upper Yukon"), and Yukon River-Teslin headwaters ("Teslin"). Spawner and return abundances among the CUs varies considerably and is primarily assessed via a monitoring and sampling program located near the U.S.--Canada border. In addition, there are assessment sites throughout the Canadian portion of the watershed, which in recent years have been operated by Yukon First Nations, Yukon Energy Corporation, or consultants [Figure \@ref(fig:fig-map-assess), @JTC2025Report]. Sampling for genetics on the spawning grounds has helped support the development of a genetics baseline which has been used to determine population and CU delineations and has been used for genetic assignment of Yukon Chinook salmon (Figure \@ref(fig:fig-map-gsi)).

Based on genetic assignments from fish sampled at the U.S.--Canada border, the Middle Yukon has averaged 43% of the Yukon Chinook SMU (1985--2024, Table \@ref(tab:tab-cons-unit-smu), Table \@ref(tab:tab-CU-gsi-annual-summary)). During this time frame, the Pelly, Northern Yukon, and Teslin CUs have averaged greater than 10% of the SMU, while the remaining CUs ranged 1%-6%. The Middle Yukon CU component has increased nearly two fold since the early years of the sampling program to a recent 10-year average of 58%. Meanwhile, Chinook salmon assigned to the Northern Yukon, Pelly, White, Stewart, and Teslin CUs have declined 30%-60%. The Nordenskiold CU has remained relatively consistent, producing a small component of the SMU (approximately 1%), while the Upper Yukon CU has increased slightly over time to nearly 5%. Similar information is not available for the Porcupine SMU, and 'total' (SMU) or CU-level border passage estimates refer passage Eagle, which include only the Yukon Chinook SMU (Figure \@ref(fig:fig-map-assess)).

Yukon Chinook salmon have a stream-type life history where fry remain in streams, rivers or lakes prior to out-migrating to the Bering Sea as 1- or 2-year-old smolts [@bradford2009freshwater], though occasionally age-0 smolts have been observed [@bradford2008]. During the first summer, fry will migrate into non-natal streams, sometimes up to 75 kilometers upstream or hundreds of kilometers downstream in search of optimal foraging and rearing habitats [@bradford2008; @daum2011]. Smolt out-migration is believed to be direct and occurs between April and June but understanding of smolt behaviour and out-migration timing is limited due to logistical constraints during the sampling period as smolts can migrate under ice [@bradford2008; @wilson2025].

Once smolts reach the Yukon River estuary, they exit the area by July or August [@howard2017; @myers2010]. Juveniles move offshore into the northeastern Bering Sea and are found in depths greater than 30 meters by September – October. They overwinter in the southeastern Bering Sea at the edge of the shelf break [@myers2010; @murphy2023]. Juvenile and immature Chinook salmon spend summers in the central Bering Sea and winters in the southeastern Bering Sea [@myers2010]. After spending 2--6 years at sea, mature adults return to the shallow northeastern Bering Sea in the early summer [@myers2010; @wilson2025]. 

Adult Yukon Chinook salmon begin their upstream freshwater migration in May to June each year [@brown2017; @wilson2025]. Spawning populations located further upstream tend to return later on average, when compared with populations lower in the Canadian portion of the drainage [@connors2022]. Performing one of the longest freshwater migrations known for Pacific salmon, they traverse approximately 2,000 km in 30 days to reach the U.S.--Canada border in late June – August [@eiler2015migratory; @wilson2025]. From here, the distance to spawning habitat varies by population, ranging from less than 100 km to over 1,000 km [@brown2017], and spawning is completed by approximately mid-September [@JTC2025Report; @wilson2025]. Adaptation to this long migration has resulted in Canadian-origin Yukon River Chinook salmon being, on average, older and larger, with a higher fat content when compared to other populations in the basin [@eiler2015migratory].
