# STOCK STATUS AND TRENDS {#sec:status-trends}

## OVERVIEW OF ASSESSMENT AND SOURCES OF DATA

A detailed review of assessment projects for Yukon Chinook salmon is provided in @pestal_review_2022. This data review spanned assessment projects for Chinook salmon across the Yukon River basin including mainstem passage (e.g., sonar, fishwheels, and mark-recapture projects), tributary spawning escapement (e.g., weir, tower, aerial, and sonar projects), harvest estimation, and associated biological sampling (e.g., genetics and age, sex, and length information for stock apportionment).

Briefly, the number of adult Chinook salmon migrating into the Canadian portion of the mainstem Yukon River has been estimated using a variety of methods over the past four decades, largely focused on the Yukon Chinook SMU. Fishwheels and a mark-recapture program operated in several locations near the border (White and Sheep rocks) from the early 1980s to the mid 2000s to estimate abundance and collect biological samples. In 2005, a sonar site and drift gillnet test fishery were established near Eagle, Alaska, to also estimate border passage and collect biological samples, and this assessment project has continued to present. Within the Canadian portion of the Yukon River, spawning escapement has been enumerated at various tributaries using foot, aerial, and sonar based assessment methods (Figure \@ref(fig:fig-map-assess); Table \@ref(tab:assess-proponents)). Many of these assessment projects have changed methods over time and/or have been relatively short in duration (Figure \@ref(fig:fig-trib-spawn)). The number of adult Chinook salmon migrating into the Canadian portion of the Porcupine River for the Porcupine River SMU has been estimated using sonar near the community of Old Crow since 2014.

Surface trawl surveys targeting juvenile Chinook salmon in the northern Bering Sea have been used most years since 2003 to derive an estimate of the abundance of Yukon River salmon stocks (Canadian, middle Yukon [Alaska], and lower Yukon [Alaska]) during their first summer at sea [@murphy2023]. These data have been used to forecast adult returns [@JTC2025Report], understand juvenile Chinook salmon marine ecology, and shed light on life stage specific drivers of survival [@howard2023; @cunningham2018]. 

Harvest of Chinook salmon in Yukon Territory has occurred in First Nations fisheries, commercial, domestic, and public angling fisheries, while in Alaska fisheries have included subsistence, commercial, and sport. In Alaska, harvest of Chinook salmon was historically apportioned to lower, middle, and upper/Canadian stocks, by age, using scale pattern analysis. Since 2003, harvest of Yukon Chinook salmon in Alaska by age and stock of origin has been estimated using genetic methods. In Canada, harvests have been estimated from commercial landings, recreational catch cards, and from communal harvest information provided by individual First Nation Lands and Resources staff to DFO.

Yukon River Chinook salmon are caught as bycatch in Bering Sea Aleutian Islands (BSAI) groundfish fisheries along with other salmon stocks from Alaska, the west coasts of Canada and the United States, eastern Asia, and Russia. Canadian-origin Yukon River Chinook salmon have typically made up a relatively small percentage (2–5%) of the total catch in recent years (2011–2016), and it is estimated that on average \~1% of the total annual return is caught in these fisheries [@ianelli_chinook_2018], though at times it has been greater and impacts on individual CUs are not known. Because harvest in BSAI fisheries is a relatively minor portion of total returns, and because estimates of harvest are not available for all years, we did not explicitly account for BSAI fisheries interceptions of Canadian-origin Yukon Chinook salmon in our analyses.

Biological information on the Yukon Chinook SMU has been collected annually from the fishwheels at White and Sheep rocks (most years from 1985–2008) and the gillnet test fishery at Eagle (2005–present) to determine fish age, sex, and length. Samples have typically been taken over the annual upstream adult migration period, with the number of samples taken each day roughly proportional to daily passage [@connors_incorporating_2020]. Genetic material has been recovered from 150–300 archived scale samples for most years between 1985–2005, and since then 200–1000 tissue samples have been taken per year for genetic stock assignment. These samples have been used to assign individual fish to one of nine CUs via microsatellite markers (1985–2016) or Single Nucleotide Polymorphisms (SNPs, 2017–present, Appendix \@ref(app:first-appendix)).

A state-space run reconstruction and spawner-recruitment model for the Yukon Chinook SMU was recently developed [@connors_estimates_2023]. The model can be fit to data from various assessment projects that estimate mainstem passage, harvests, tributary escapements, stock proportions, and age composition and has been used to derive annual estimates of total harvest, escapement and returns, by age, for mainstem Yukon River Chinook salmon (i.e., not including Porcupine Chinook salmon) [@JTC2025Report].

## RUN RECONSTRUCTION AND SPAWNER-RECRUITMENT MODELS

We reconstructed spawner abundance and population dynamics for the CUs in the nine CUs in the Yukon Chinook SMU following the approach described in @connors2022. This approach consisted of three overarching steps: (1) estimate daily CU composition (i.e., proportion of daily total abundance assigned to each of nine CUs) in test fisheries at the U.S.--Canada border via molecular analyses of archived scale and tissue samples collected from returning spawners; (2) estimate annual CU-specific border passage and abundance via a state-space run-reconstruction model fitted to daily estimates of total border passage and CU composition; and (3) characterize CU scale population dynamics and estimate biological benchmarks by fitting age-structured, state-space spawner (or egg mass) recruitment models to estimated spawner abundances, harvest, and age composition. Details on the molecular analyses, run-reconstruction model, and spawner-recruitment analyses and estimation of benchmarks are detailed in Appendix \@ref(app:first-appendix), \@ref(app:second-appendix), and \@ref(app:third-appendix), respectively. Due to data limitations, CU-level scale analysis for the Porcupine Chinook SMU was not able to be undertaken. 

## BIOLOGICAL BENCHMARKS AND REFERENCE POINTS

### CONSERVATION UNIT BIOLOGICAL BENCHMARKS

Biological benchmarks are used to assess the biological status of CUs under Canada's Wild Salmon Policy [WSP, @holtEvaluationBenchmarksConservation2009, Table \@ref(tab:benchmarks)]. One commonly used lower biological benchmark is $S_{GEN}$, the spawning abundance that is expected to lead to recovery to $S_{MSY}$ (the spawner abundance at maximum sustained yield) in one salmon generation in the absence of fishing under equilibrium conditions [@holtEvaluationBenchmarksConservation2009]. This benchmark is meant to identify when there is high risk of irreversible harm to the CU and is aligned with a Committee on the Status of Endangered Wildlife in Canada (COSEWIC) assessment of “endangered”. A commonly used upper biological benchmark is 80%$S_{MSY}$ which is 80% of the spawner abundance associated with maximum sustainable yield under equilibrium conditions. These two benchmarks ($S_{GEN}$ and 80%$S_{MSY}$) are typically used to assess WSP status when there is sufficient data to estimate spawner-recruitment relationships at the CU scale, or information on freshwater spawning and rearing habitat capacity are available. Other alternatives have been applied in some contexts (e.g., 20% and 40% of $S_{MSR}$ [spawner abundance associated with maximum recruitment]) as a proxy for the lower and upper WSP benchmarks, respectively.

While the use of MSY-based benchmarks under the WSP and DFO’s Precautionary Approach framework [@DFO2009PA] is consistent with international standards, they have been criticized for being explicitly tied to yield based objectives [@frid2023re], difficult to estimate, and sensitive to temporal variation and trends in intrinsic productivity [@holt2020impact]. For these reasons we used benchmarks based on estimates of the spawner abundance associated with maximum returns ($S_{MSR}$) to assess the biological status of CUs in the Yukon SMU instead (Table \@ref(tab:benchmarks)). Specifically we used 20% and 40% of $S_{MSR}$ as lower and upper biological benchmarks, respectively [@holtEvaluationBenchmarksConservation2009]. We argue these alternatives are more biologically based (because they are not tied to yield based objectives), easier to estimate, and less sensitive to temporal variation in intrinsic productivity than MSY based benchmarks. While $S_{MSR}$ based benchmarks can be slightly more biologically conservative than $S_{MSY}$ based ones in some systems they are still generally consistent with the intent of upper and lower benchmarks under the WSP and in their application to status assessments across salmon CUs in the Pacific Region. In addition, the use of $S_{MSR}$ based benchmarks is aligned with the proposed use of $S_{MSR}$ based reference points at the SMU scale (see next section).  

We also used 100% of $S_{MSR}$ as an illustrative CU rebuilding target to quantify rebuilding potential and the biological consequences of alternative fisheries management measures (Section \@ref(sec:impact)). We argue this target is better aligned with Indigenous and ecosystem based management principles and the concept of “take only what you need and leave lots for the ecosystem” [@reid2022protecting] than $S_{MSY}$ based targets. Because they are not tied to concept of maximum sustainable yield and are associated with lower fishery removals, they allow for greater resilience to climate change and other uncertainties, and better preserve ecosystem functions, both principles often found in Indigenous Knowledge [@frid2023re]. These CU rebuilding targets were based on analyses that explicitly attempted to account for changing reproductive potential due to shifts in age structure and size at age in female Chinook salmon (described in detail in section on "Escapement Quality" in Appendix \@ref(app:third-appendix)). 

Consistent with emerging recommendations for Pacific salmon [@Holt2025TVguidance], our estimates of biological benchmarks (and reference points; see next section) were derived from spawner-recruitment, or egg mass-recruitment, models that assumed long-term stationary dynamics as opposed to models that allowed intrinsic productivity to vary through time (Appendix \@ref(app:third-appendix)).   

We recognize that there is an inherently subjective dimension to the selection of biological benchmarks and so to be transparent about our use of $S_{MSR}$ based benchmarks and rebuilding targets at the CU scale we compared their values to other commonly used ones with, and without, also attempting to explicitly account for recent demographic characteristics of spawners (Figure \@ref(fig:fig-bench-compare)).

### STOCK MANAGEMENT UNIT REFERENCE POINTS {#sec:smu-rps}

A Limit Reference Point, Upper Stock Reference Point, and maximum Removal Reference need to be defined for the Yukon Chinook salmon Stock Management Unit (SMU) to meet the Fish Stocks provisions of the *Fisheries Act* [@bill201968] (Table \@ref(tab:refpoints)). Data limitation did not allow for development of these same reference points for the Porcupine Chinook salmon SMU (only \~10 observations of spawner abundance, Figure \@ref(fig:fig-map-assess)). 

The Limit Reference Point (LRP) is intended to avoid serious harm to the stock and resultant impacts to the ecosystem, associated species, and/or a long-term loss of fishing opportunities [@barrett2024technical]. Regional and national DFO guidance is that LRPs for salmon SMUs should be ‘CU (Conservation Unit) status-based’ to meet the Fish Stocks provisions [@holt2023guidelines]. This means that a SMU is below its LRP if any component CUs are in the WSP ‘red’ status zone. The WSP rapid status framework [@pestal2023state] is the default approach to formally assess the WSP status of each CU in an SMU in order to meet the Fish Stocks provisions. Wild Salmon Policy statuses under this framework use multiple abundance and trends in abundance metrics to assess status, and the framework emphasizes iterative local expert review.

The Upper Stock Reference (USR) point is the aggregate SMU spawner abundance at which socio-ecological objectives for the system are expected to be met, and above which maximum allowable harvest rates (up to the Removal Reference point) can be sustained. The USR should also be set at an appropriate distance above the LRP to provide (a) sufficient opportunity for the management system to recognize a declining stock status and (b) time for management actions (e.g., reduced harvest) to have effect. The Removal Reference is the maximum acceptable harvest rate the SMU can be subject to and is typically set to be less than or equal to the removal rate associated with maximum sustainable yield ($U_{MSY}$).

Other aggregate abundance based reference points can be defined for an SMU. A 'Fishery Reference Point - Lower' is the aggregate SMU spawner abundance below which all fishery removals should be limited to the maximum extent possible and below which there is a high risk of serious and irreversible harm to the stock. This is referred to as a lower fishery reference point to avoid confusion with the CU status-based LRP noted above. This type of reference point is helpful for informing management since assessment and fishery decisions are often abundance based and so can be operationalized. 

We used a CU-status based LRP to formally assess SMU status relative to the LRP per national guidance where CU statuses are based on applying the rapid status assessment framework for Pacific salmon under Canada's WSP [@pestal2023state, Appendix \@ref(app:fourth-appendix)].

We propose that an USR equal to the median estimate of $S_{MSR}$ for the Yukon Chinook salmon SMU, when changes in demographics are taken into account [86,000 spawners based on @connors_estimates_2023], be used for the SMU (Table \@ref(tab:refpoints)). This could be considered the aggregate spawner abundance at which socio-ecological objectives for the system are potentially maximized, and above which maximum allowable fishery removals could occur. We also propose that this be considered as the rebuilding target for the Yukon Chinook salmon SMU.

We propose that the USR be based on analyses of the Yukon Chinook Salmon at the SMU scale and not analyses of component CUs because we consider these to be the most scientifically defensible estimates of stock aggregate dynamics, and hence reference points. This is because they are based on an integrated run-reconstruction and spawner-recruitment models fit to data from various assessment projects that estimate mainstem passage, harvest, tributary escapements, stock proportions, and age composition. In addition, this model is used bilaterally under the Yukon River Salmon Agreement to derive annual estimates of total harvest, escapement and returns, by age, for Canadian-origin Yukon Chinook salmon. While this model does not explicitly take CU scale dynamics into account, the closed loop simulations described in Section \@ref(sec:impact) evaluate CU scale consequences of operationalizing the SMU reference points we propose and other harvest control rules that have been used or considered for this system.

We propose a maximum Removal Reference point for the Yukon Chinook salmon SMU that is equal to the long-term average $U_{MSY}$ for the least productive CUs (Table \@ref(tab:refpoints)). Adopting this reference point would help to ensure that maximum allowable fishery removals, in mixed-CU mainstem fisheries in Alaska and Yukon, are unlikely to overfish the least productive CUs in the system.

Lastly, we propose a Fishery Reference Point - Lower equal to 25,000 spawners for the Yukon Chinook SMU (Table \@ref(tab:refpoints)), which is the average SMU spawner abundance associated with no greater than 50% chance of at least one CU falling in the Wild Salmon Policy Red status zone based on the forward simulations described in (Section \@ref(sec:impact)). To be consistent with the intent of the *Fisheries Act*, at aggregate returns below this reference point we propose that fishery removals be limited to the extent possible, while above the reference point removals can progressively be increased to the Removal Reference point (the maximum removal rate when the USR point is met).

All of the above reference points are proposed for the Yukon Chinook SMU only. There is very limited data for the Porcupine SMU (\~10 observations of spawner abundance, Figure \@ref(fig:fig-map-assess)) which precluded us from characterizing its dynamics and/or estimating reference points for it.

## CONSERVATION UNIT STATUS AND TRENDS

### RUN-TIMING AND RECONSTRUCTED SPAWNER ABUNDANCES

Run-timing, as inferred by the timing of passage from Alaska into Yukon, varied among CUs (Figure \@ref(fig:fig-run-timing)). Conservation Units with Chinook salmon that spawn in the lower (more northern) portion of the Canadian Yukon River basin tended to return, on average, earlier than those in the upper (more southern) portions of the basin. Chinook salmon from the Middle Yukon and Upper Yukon CUs tended to return later than Teslin fish, the longest migrating Chinook salmon in the Yukon River. Chinook salmon from the Nordenskiold CU tended to have the latest, and most variable, run-timing. This run-timing variation results in an average return migration duration that is approximately twice as long (~70 days) as the average individual CU migration (~35 days).

All CUs exhibited considerable inter-annual variation in reconstructed spawner abundance over time (Figure \@ref(fig:fig-CU-spawn)). The Middle Yukon CU had on average the largest spawning abundances (~13,000) followed by the Pelly (~10,000) and Northern Yukon (~7,500) CUs. The White (~3,800) and Nordenskiold (~1,900) CUs had the smallest average spawner abundances. Across CUs spawner abundances in the most recent generation (2018--2024) were on average 46% lower than preceding ones (1985--2017). The Northern (68% lower),  Pelly (62% lower), and White (60% lower) CUs have experienced the largest magnitude declines. 

There was not strong evidence for changes in the proportional contribution of different CU to total spawning abundance over time (Figure \@ref(fig:fig-CU-comps)). This is in contrast to the apparent increase in the contribution of the Middle Yukon CU over time based on the raw GSI based estimates of CU contributions to border passage over time [e.g., Appendix B24 in @JTC2025Report]. The likely reason for these differences is that the raw estimates of contributions are confounded by the sometimes unrepresentative genetic sampling of total returns. For example, in recent years (e.g., 2020--2024) genetic samples tended to be biased toward the second half of the run to varying degrees and because the Middle Yukon CU tends to have a run-timing that is slightly later than peak of aggregate return (Figure \@ref(fig:fig-run-timing)) it may be over represented in the raw genetic proportions. 

Reconstructed CU spawner abundances were not fitted to data from tributary scale assessments, but tended to correlate positively with them (Figure \@ref(fig:fig-trib-vs-CU-spawn)). Tributary assessments that indexed a larger fraction of the total CU and/or were higher precision methods (e.g., Takhini and Klondike sonars, Tatchun weir) tended to have the strongest positive correlations with reconstructed CU scale spawner abundances. One exception was the Whitehorse fishway that had little relationship with reconstructed spawner abundance for the Upper Yukon CU, possibly because fish enumeration at the fishway is confounded by relatively low rates of passage for returning adults. 

### SPAWNER-RECRUITMENT RELATIONSHIPS
There was clear evidence of heterogeneity in intrinsic productivity ($\alpha$) and spawner abundance associated with maximum recruitment ($S_{MSR}$) across CUs (Figure \@ref(fig:fig-par-ref-hist); Tables \@ref(tab:pars-ref-pts) and \@ref(tab:pars-sr)). Mean estimates of intrinsic productivity ranged from 2.25 to 7.62 recruits-per-spawner and $S_{MSR}$ ranged from ~ 1,600 to 20,000 spawners. These intrinsic productivities translate into harvest rates predicted to maximize long-term harvest (i.e., $U_{MSY}$) that range from ~35% to 60%. Most CUs showed some visual evidence of overcompensation with modestly declining recruitment at relatively high spawner abundances, and for many of the CUs the largest recruitments were observed in brood years with relatively low to moderate spawning abundances in the early part of the time series (1985–1995 brood years, Figure \@ref(fig:fig-CU-SR)). Interannual variation in recruitment was positively correlated among CUs (mean pairwise correlation of ~0.5) and was strongest for CUs that were geographically closest to each other. There was strong evidence of time-trends in recruitment and productivity over time (Figure \@ref(fig:fig-prod-trends)) with productivity estimated to have declined by an average of 60% across CUs between the late 1980s and the early 2020s, though Nordenskiold brood years in the mid 2000s appeared to have a large spike in productivity. 

### ESCAPEMENT QUALITY
As has been well documented previously [@ohlberger_demographic_2018;@ohlberger_reproductive_2020;@connors_estimates_2023], age, size, and sex ratios, as measured at the U.S.--Canada border, have changed to varying degrees over time (Figure \@ref(fig:fig-asl)). The proportion of returning fish that were sexed as female declined from an average of approximately 53% in the 1980s to 46% in the 2020s, with considerable interannual variation (as high as 59% in 1989 and low as 31% in 2023). In contrast, there is little evidence of declines in female size at age (Figure \@ref(fig:fig-asl)b). Female Chinook salmon age composition has changed considerably over time. In the 1980s, approximately 20% of females were seven year olds, 70% were six year olds, and fewer than 10% of females returned on average as five year olds. By the 2020s an average of 5% of females returned as seven year olds, 70% as six year olds and 25% as five year olds (Figure \@ref(fig:fig-asl)c).

When the relationship between female size and fecundity [@ohlberger_reproductive_2020] is taken into account, these observed demographic changes translate into a marked decline in average reproductive output per spawner (Figure \@ref(fig:fig-asl)d). Specifically, the average total eggs per spawner declined by ~25% from the late 1980s to the early 2020s. 

REVIEW FROM HERE...
These changes result in modest differences in the inferred shape of the relationship with recruitment when spawners are the measure of reproductive output versus when total egg mass is used instead (Figure \@ref(fig:fig-CU-EMR), Figure \@ref(fig:fig-CU-SR)). As a result of the observed declines in reproductive output, the spawner abundance expected to maximize recruitment ($S_{MSR}$), given recent (2015--2024) demographic characteristics, was estimated to be on average 40% greater across all CUs than spawner abundance estimated given historical (1985--1995) demographic characteristics (Table \@ref(tab:demo-ref-pts)). In contrast, $S_{MSR}$ given recent (2015--2024) demographic characteristics was estimated to be on average 6% greater across all CUs than when demographic change was not taken into account (Table \@ref(tab:demo-ref-pts)) but this was highly variable (65% to -45%) and for several CUs estimates of $S_{MSR}$ corresponded to smaller spawner abundances when demographic change was explicitly accounted for (i.e., Big Salmon, Northern Yukon, Upper Yukon CUs). The reason why estimates were lower for some CUs may be due to subtly different shapes between the two alternative reproductive output (i.e., spawners vs. total egg mass) and recruitment relationships; CUs like Big Salmon and the Northern Yukon and Upper Yukon appeared to have more evidence for overcompensation when considering egg mass and this could in turn result in estimates of the corresponding spawner abundance expected to maximize recruitment being lower than when the reference point is based on a total spawner to recruitment relationship. 

## WILD SALMON POLICY RAPID STATUS ASSESSMENTS
An assessment of CU biological statuses was carried out following the methods detailed in the Wild Salmon Policy (WSP) rapid status framework [@pestal2023state]. The key inputs into these assessments were biological benchmarks and time series of reconstructed spawner abundances in most cases, but tributary assessments were used instead in some cases (Table \@ref(tab:pars-ref-pts)). The data inputs and resulting statuses were decided through a series of meetings with subject matter experts. The outcome of these assessments are briefly summarized here; more details are provided in Appendix \@ref(app:fourth-appendix).

Within the Yukon Chinook SMU, four CUs (Nordenskiold, Upper Yukon, Stewart, and White) were assessed as in the Red status zone due to spawner abundances over the most recent generation being below an absolute abundance lower threshold of 1,500 spawners. These statuses were based on run-reconstruction model estimates of spawner abundance with the exception of the Upper Yukon CU which instead was based on tributary assessment projects that are believed to assess the majority of the CU. The Teslin and headwaters CU was assessed as in the Red status zone based on trends in spawner abundance from two long-running aerial surveys. These assessment projects were considered to be more consistent with local observations and expert feedback than run-reconstruction based WSP status. The WSP rapid statuses for other CUs in this SMU were assessed as in the Amber status zone (Figure \@ref(fig:fig-rapid-status)).  

Status assessment for the Porcupine Chinook salmon SMU is limited to the Porcupine and Old Crow CUs, as the Salmon Fork CU is data deficient. The Porcupine and Old Crow CUs have been jointly assessed by sonar beginning in 2014. Since then the two CUs have averaged ~4,000 during the first six years, and have fallen to ~400 in most recent four years (2021--2024). The most recent generation (2019--2024) geometric mean for the CUs combined is 695 which is well below the absolute abundance lower threshold of 1,500. Both CUs were therefore assessed as in the Red WSP status zone and the SMU is assessed as being below its CU-status based LRP.   

## SMU STATUS AND TRENDS
Aggregate returns, harvest and spawner abundances for the Yukon Chinook SMU were derived from updated fits (through 2024) of the model described in @connors_estimates_2023. 

The Yukon Chinook salmon SMU experienced relatively large run-sizes from 1981--1995, followed by a sharp decline in the late 1990s, a modest recovery in the mid-2000s, and then a general decline since with the lowest observed run-sizes on record in 2021--2024 (Figure \@ref(fig:fig-smu-trends)). Overall the SMU declined by ~87% from 1981--2024. In contrast to run size, spawning escapements have varied from year to year but have been relatively consistent over time (grey bands in Figure \@ref(fig:fig-smu-trends)a) with the exception of the very low spawning abundances in recent years. 

Aggregate SMU harvest has also varied considerably over time, and realized harvest rates have ranged from an average of 68% in the late 1980s and early 1990s to 18% over the most recent decade (Figure \@ref(fig:fig-smu-trends)b). In the last four return years harvest was dramatically curtailed and averaged 3%--8%.

The Yukon Chinook salmon SMU is assessed as being below its CU-status based LRP because there are four CUs that were assessed as being in the Red status zone. Aggregate spawner abundances over the most recent generation (6 years) averaged 25,852 which is slightly above the proposed lower fishery reference point of 19,000 and well below the proposed upper stock reference point of 95,000. The harvest rate over this same time period averaged 16%. 

The Porcupine SMU is also below its CU-status based LRP because there two CUs are in the Red status zone, but data limitations preclude abundance and harvest trend metrics for this SMU.
