---
bibliography: bib/refs.bib
output: word_document
---

# ANTHROPOGENIC, ECOSYSTEM, AND CLIMATE FACTORS AFFECTING THE STOCK {#sec:factors}

The past decade has seen a considerable amount of research into anthropogenic, ecosystem, and climate factors that may have contributed to the recent and long-term declines in body size and productivity of Yukon Chinook salmon. Anthropogenic climate change is causing clear, directional changes in the ecosystems used by Yukon River Chinook salmon, but is also likely to increase the variability of conditions experienced year-to-year. The arctic is warming up to four times faster than the globe [@rantanen2022], meaning that Northern populations of salmon are likely to experience more rapid change than more Southern ones. The northernmost populations in the Yukon Chinook stock (i.e., Porcupine SMU) should be considered more vulnerable overall to future climate-related changes in freshwater environments. While the Yukon River watershed is relatively minimally modified by human activity, some populations are subject to large localized anthropogenic impacts (e.g., from mining, hydroelectric facilities, etc.) in addition to overarching environmental change. Taken together, these factors impact every life stage and ecosystem used by Yukon Chinook salmon. The sections below, and Table \@ref(tab:tab-factors-summary), summarize what is currently known about factors affecting the stock by life stage, but is not an exhaustive review. Additional factors affecting the stock pertaining to habitat are found Section \@ref(sec:HABITAT), and impacts from fisheries were described in Section \@ref(sec:status-trends).

## Migrating/Spawning Adult

The adult freshwater return migration of Canadian-origin Yukon Chinook salmon is one of the longest of any Pacific salmon populations, up to 3,200km [@brown2017], and this is believed to be the life stage where both environmental and intrinsic factors (e.g., age and/or size) are most limiting the productivity of Yukon Chinook salmon and present the highest risk to the future of the stock [@howard2023]\footnote{von Finster, A., Murdoch, A., Gill, J., Hawkins, T., Hodgson, J., and Knight, K. In press. Issues Facing Canadian-origin Yukon River Chinook Salmon: A Review of Limiting Ecosystem and Habitat Factors.\label{vonfinsteretal}}. Over their long freshwater migrations, Canadian-origin Yukon Chinook salmon can be exposed to a wide range of temperature and flow conditions, especially those that spawn in smaller tributaries. High maximum daily temperatures and maximum weekly temperatures are negatively associated with the productivity of some CUs (White, Stewart, and Pelly) [@feddern2024; @murdoch2024]. This is hypothesized to occur via reduced survival and spawning success with effects that carry over to juvenile production in the following generation [@vonbiela2020; @murdoch2024]. Heat stress begins at 18$^\circ$C and intensifies at 21$^\circ$C for Yukon River Chinook salmon [@bowen2020; @usepa2003]. Adult Chinook salmon that experienced warmer water temperatures and lower discharge in the mainstem Yukon River during their return migrations tended to produce fewer juveniles per spawning adult [@howard2023]. The timing of upstream migrations differs among CUs (Figure \@ref(fig:fig-run-timing)), likely in part due to the thermal regimes in which eggs incubate [@connors2022], and they may be differently adapted to temperatures during their spawning migration. This adaptation along with cumulative heat exposure for longer-migrating fish may explain variation among CUs in their relationships with migration temperatures, for example, the productivity of mainstem CUs tend to be minimally associated with migration temperature, while the Pelly, Stewart, and White CUs tend to be the most strongly related [@feddern2024].

Pathogens and disease are also a concern in spawning adults, and their impact is likely mediated by environmental conditions (e.g., temperature during return migrations). *Ichthyophonus hoferi* is a pathogen that can infect immature or maturing Chinook salmon in the marine environment [@murphy2023; @murphy2024_youtube], but infection is most likely to impact survival and reproductive success during spawning migrations. It is believed to infect female Chinook salmon more than males [@kocan2004]. ). Infections appear to be most severe near the midpoint of migration for Canadian-origin Yukon Chinook salmon (between river entry and U.S.--Canada border) and it is believed that *Ichthyophonus* results in significant en route mortality of Yukon River Chinook downstream of the U.S.--Canada border, though it has not been quantified\textsuperscript{1} [@liller-ich2023]. 


Another issue affecting spawners is thiamine deficiency, a condition that can arise in part from a poor diet in the marine environment  [@larson2019]. Low thiamine levels in spawning adults and subsequently low thiamine stores in eggs may be contributing to lower run sizes [@larson2019; @howard2023], but research on its impacts and causes in Yukon River Chinook salmon is limited. Although CU-specific data are not available, thiamine deficiency likely disproportionately affects Yukon River Chinook salmon with the longest migrations (i.e., Teslin and Stewart CUs), as evidenced by low thiamine levels observed on the spawning grounds of far-migrating Chinook salmon [@larson2019].

In addition to these biotic and abiotic stressors, hydroelectric facilities at Mayo and Whitehorse Rapids pose localized challenges to adult migration. The Mayo facility, built in the 1950s, obstructs adult fish passage and locally extirpated Chinook Salmon from the upper reaches of the Mayo River and Mayo Lake, in the Pelly CU. Gravel starvation and channel works potentially contribute to reduced quality of spawning habitat below the dam as well\textsuperscript{1}. The Whitehorse Rapids hydroelectric facility (Upper Yukon CU) and storage dam have fish ladders for adult passage, but the efficacy of the ladder is low (31%), particularly for females [13%, @twardek2023adult]. Many female salmon in the Yukon River downstream of the Whitehorse Rapids facility were found to have retained (unspawned) eggs, with 16% of total fecundity retained there compared to 2% in the Teslin River [@jessup2024michie]. It is hypothesized that females who fail to pass the Whitehorse Rapids fishway  either do not find suitable spawning locations below the dam or lack energy to complete spawning [@jessup2024michie].

## Egg, fry, and smolt

The survival of salmon during their incubation (egg) and freshwater rearing life stages is influenced by hydrology and broader climate conditions. There is some evidence that above average streamflows during egg incubation in the fall are negatively associated with Yukon Chinook salmon productivity [@feddern2024]. Warmer winter temperatures in freshwater during incubation and rearing are associated with above average Yukon Chinook salmon productivity [@murdoch2024]. However, it is considered unlikely that changes in egg survival are principally responsible for the declining productivity observed in Yukon Chinook salmon populations [@lamborn2025].

Climate and hydrological conditions during fry rearing are also associated with Yukon Chinook salmon productivity. High levels of precipitation during the fry stage are associated with lower productivity [@murdoch2024]. The date of Yukon River ice out (break-up of river ice in spring) is associated with smolt outmigration timing, and earlier ice out years have been linked with increased survival and productivity for Chinook salmon [@murdoch2024; @cunningham2018]. In smaller tributaries, the formation of stream ice (aufeis) can reduce or even stop stream flow, which can be fatal to rearing salmon [@bradford2001]. Climate change is expected to result in earlier ice out, but also increase winter temperature variability, potentially increasing the prevalence of irregular ice formations like aufeis. Observed impacts of climate change on rearing Yukon Chinook salmon appear to have complex causes, and future responses are uncertain. The arctic is warming more rapidly than more Southern latitudes [@rantanen2022], meaning that the freshwater habitats used by more Northern CUs (Porcupine, Old Crow, and Salmon Fork) are likely to experience the most severe cumulative impacts of climate change, resulting permafrost thaw, and glacial retreat, which are discussed in \@ref(sec:HABITAT). 

The Whitehorse Rapids hydroelectric facility requires smolts from the Upper Yukon CU to pass downstream over the spillway, through the power generation turbines, or through the fish ladder. Recent studies indicate that downstream mortality rates could be as high as 30%, and could stun juveniles as they pass through the facility, increasing their vulnerability to predators downstream [@twardek2023juve]. It is possible that flow regimes and gravel starvation from the Mayo hydroelectric facility are impacting incubation and rearing below the dam, but the extent of impact is unclear\textsuperscript{1}.

Placer mining, nearly all (96%) of which occurs in the central Yukon [@vanloon2025], can have a large impact on stream beds, banks, and surrounding terrain. Sluicing, road development, and tailings ponds can increase fine sediment suspension, deposit sediment downstream, and cause bank destabilization. Sedimentation can impact the incubation of salmon eggs by impeding oxygen absorption, thereby reducing the egg-to-fry survival rate [@jensen2009]. Elevated levels of sedimentation and turbidity can also can impact fry survival by reducing primary and secondary productivity of aquatic systems, and may also change the behaviour of fry [@dfo2000]. Mining activities can also release heavy metals and change the pH of streams, which may have deleterious effects on eggs and fry. Current regulations for placer mining do not consider cumulative impacts of multiple mining locations throughout a watershed, and mining takes place in multiple Yukon River Chinook salmon CUs. Most of the gold produced by placer mining (47%) takes place near Dawson in the Northern Yukon and White CUs, with smaller operations near the lower Stewart River, Mayo, the South McQuesten River, Kluane, Whitehorse, Livingstone, and Dawson Range [@vanloon2025]. Cumulatively, placer mining for gold takes place in six of the twelve Yukon River Chinook salmon CUs (Northern, White, Pelly, Middle Yukon, Upper Yukon, and Teslin). Additional water quality changes can come from permafrost melt through the release of stored heavy metals or toxins\textsuperscript{1}.

## Juvenile
The climatic and ecosystem conditions that salmon encounter in their first year in the marine environment have a major impact on growth and survival. Similar to river ice, sea ice in the Bering Sea is related to the outmigration of Yukon Chinook salmon, and productivity is higher when sea ice melts early [@feddern2024; @bradford2008; @howard2017]. Less ice cover in the estuary  may also be associated with increased food resources available to juvenile salmon [@murphy2021]. Earlier outmigration and abundant food resources allow higher growth and survival in the first months of marine life, which are considered a critical life stage with relatively high mortality [@cunningham2018]. Warmer winter temperatures in the first year at sea are also associated with higher productivity for Canadian-origin Yukon River Chinook salmon, but there is less evidence of a relationship with summer temperatures [@feddern2024; @murdoch2024]. Future climate change will likely continue to reduce sea ice and increase winter temperatures, but it should not be assumed that this will result in positive outcomes for Yukon River Chinook salmon. The rate of ocean warming in the Bering Sea is several times higher than elsewhere in the North Pacific, and historically positive relationships between salmon and warm ocean conditions can erode or even reverse under new conditions (@litzow2018, @litzow2020). Warm conditions during early marine life may already have detrimental effects, for example, increasing temperatures during this life stage have been correlated with an increase in the number of jacks (salmon that return early), thereby contributing to overall declines in the average size of spawners [@murphy2021]. Furthermore, warm sea surface temperatures favour a community of smaller, less energy-dense copepods, as opposed to the larger copepods that are high-quality prey for salmon and forage fish [@siddon2023]. As a result, juvenile energy density of Yukon River Chinook salmon measured in the Eastern Bering Sea was low in 2019, during a marine heatwave [@murphy2023, @siddon2023]. Simultaneously, large numbers of rearing pink salmon in the eastern Bering Sea (primarily originating from Russia) can similarly shift the zooplankton community toward smaller copepods [@siddon2023]. The availability and quality of prey is being dually affected by both bottom-up (climate) and top-down (pink salmon) processes during a critical growth stage, potentially impacting the survival, size, and condition of salmon that return or are caught in fisheries.

Subadult and adult Chinook salmon are vulnerable to predation by apex predators including salmon sharks and killer whales, including in the Eastern Bering Sea [@seitz2019]. There is some evidence that killer whale abundance is increasing in the North Pacific generally, possibly contributing to declines in both survival and size via size-selective predation on large Chinook salmon in coastal waters [@ohlberger2019]. However, there is no research indicating the role apex predators may play in the declining size and abundance of Yukon River Chinook salmon specifically.

## Adult

Data pertaining to the adult marine life stage are relatively scarce because their habitat during this time includes offshore areas in the central and Western Bering Sea [@myers2010]. Similarly to juvenile Chinook salmon, adult Chinook may be affected by abundant pink salmon via competitive interactions [@ruggerone2016; @feddern2024; @lamborn2025]. While pink and Chinook salmon typically occupy a different trophic niche as adults [@johnson2009], pink salmon are capable of causing trophic cascades that alter the availability of prey for other salmon species  [@ruggerone2023]. The abundance of pink salmon has been increasing since the mid-1980s due in part to releases from large-scale hatcheries in Russia and Alaska. Prey quality and availability is also a concern for adult salmon, as climate change-induced shifts in the marine food web similar to those documented in the Eastern Bering Sea are likely occurring across the Bering Sea. Marine diets are the root of some conditions that present during upriver migration to spawning grounds, including thiamine deficiency and *Ichthyophonus* infection.

Suboptimal prey and increased competition for Chinook salmon combined with a projected shrinking of suitable ocean habitat [@abdul-aziz2011] are likely already contributing to poorer marine habitat conditions for adult Canadian-origin Yukon River Chinook salmon in their marine life stage. However, the high-seas habitat that Chinook salmon occupy as adults is governed by large-scale climate processes that are known to exhibit regime shift-like changes with major implications for growth and survival of adult salmon [@litzow2018]. The trends observed may not continue into the future, as the climate of the North Pacific continues to change and ecosystems shift in response.
