# ENHANCEMENT {#sec:enhancement} 
 
## HISTORY OF ENHANCEMENT OF YUKON RIVER CHINOOK SALMON 
 
Over the last 40 years several enhancement activities have been directed towards Yukon River Chinook salmon, though they have been fairly modest in nature. These activities have included hatcheries, incubation facilities, and in-stream incubation projects (Figure \@ref(fig:fig-enhance-proj)). The largest and longest running enhancement project has been the Whitehorse Rapids Fish Hatchery which began operations in 1984 as mitigation for turbine induced mortalities of migrating Chinook salmon juveniles associated with the Whitehorse Rapids Generating Facility [@ricks1996]. The hatchery was designed for a maximum capacity of 400,000 Chinook smolt 0+ reared to a weight of 2 grams. There is currently an annual release target of 150,000 smolt 0+ Chinook for compensation/mitigation purposes. To varying degrees juveniles have been adipose fin clipped and coded-wire tagged (CWT) since 1984. More recently, parentage-based tagging (PBT) was implemented beginning with the 2019 brood year. Fin clipping and tagging enables in-season hatchery genetic management by allowing hatchery fish to be identified and reducing total hatchery origin broodstock as necessary. In theory it also provides harvest and assessment information though recoveries of clipped and tagged fish but harvest sampling programs are likely not robust enough to reliably estimate encounters in fisheries [@connors_estimates_2023]. In addition to its primary mitigation objective, the Whitehorse Rapids Fish Hatchery supports stewardship and education activities by annually providing up to 2,000 eggs for local Stream to Sea classroom incubators.  
 
The Whitehorse Rapids Fish Hatchery is owned and operated by the Yukon Energy Corporation. DFO's Salmonid Enhancement Program determines the hatchery production targets for the facility through an Integrated Production Planning process, which considers DFO's priorities and mandate, the Wild Salmon Policy, fish health, and hatchery-wild interactions. These plans include details on target releases by stock, release strategy and location, and fin clipping and tagging\footnote{DFO. In Press. Integrated Fisheries Management Plan Salmon Enhancement Program (SEP) data tables, Pacific Region\url{https://www.pac.dfo-mpo.gc.ca/sep-pmvs/data-donnees/index-eng.html}}. Whitehorse Rapids Fish Hatchery became the only active enhancement facility in the watershed after the McIntyre Creek Fish Incubation Facility was destroyed by a fire in 2018. Enhancement activities at Whitehorse Rapids Fish Hatchery appears to have increased total adult returns to the Upper Yukon River CU, though no dedicated work has been completed on the efficacy of the program to mitigate mortalities associated with the hydroelectric dams. 

Genetic management is a priority for in-hatchery operational planning and salmon management that has evolved over time. Recent work by @withler2018 and updated enhanced contribution guidelines [@sep2024contributionguidelines] provide guidance on the genetic risk of prolonged hatchery enhancement activities on wild stocks, identifying Proportionate Natural Influence (PNI) as a key metric to measure hatchery genetic influence. PNI is a widely applied metric to evaluate, classify, and monitor levels of hatchery influence and genetic risk to the natural adaptive state of 'integrated' populations [@HSRG2009; @HSRG2015]. Integrated populations in this context are those in which natural and hatchery origin salmon spawn in both the hatchery and natural environments, with gene flow between the two. PNI is calculated by dividing the proportion of natural origin broodstock by the combination of natural origin broodstock and hatchery origin spawners. The PNI metric is associated with specific biological designations which progress from "wild" to "integrated-hatchery", as defined in @withler2018. With an average PNI of 0.72, the Yukon River Chinook salmon populations above the fishway (part of the Upper Yukon River CU; CK-69) are considered 'integrated-transition', where natural origin salmon are in the majority, and gene flow is dominated by the natural environment (Figure \@ref(fig:fig-wh-fishway)). To minimize long-term genetic risks it is typically recommended that rebuilding programs work toward a in integrated-wild designation (PNI>0.8), where natural productivity is sufficient. 

In-stream incubators are used as a low-cost means to improve fertilization rates and in-stream egg to emergence survival. Although they have been used at multiple sites in the Yukon watershed (e.g., Deadman Creek [@edi2021deadman], Ibex Creek [@edi2021ibex], Nisultin River [@edi2023nisutlin], Fox Creek [@tkc2024foxcreek]), there is currently no centralized database of these activities. Success of in-stream incubators can be highly variable depending on site conditions, weather, and methodology, among other factors [@edi2021deadman].  

## POTENTIAL ENHANCEMENT PLANNING ACTIVITIES THAT COULD CONTRIBUTE TO STOCK REBUILDING 

Enhancement activities for rebuilding purposes should address identified bottlenecks to salmon survival and should be part of a comprehensive recovery strategy that considers habitat and harvest measures. However, enhancement for rebuilding often incurs heightened risks to wild populations and must be characterized by well-defined objectives, a clear plan to transition through recovery stages, a robust monitoring program, and strong safeguards that acknowledge the potential genetic, ecological and disease risk associated with enhancement [@dfo2013]. This can be best achieved with enhancement plans that summarize enhancement objectives, goals and intended outcomes, developed in consultation with First Nations and stakeholders. Key initial activities to consider for Yukon River Chinook salmon, drawn from guidance on conservation hatcheries, include [@bradford2025hatcheries]: 
 
  1. Identify threats and stressors that are contributing to low returns and determine if hatchery enhancement could contribute to rebuilding efforts. For example, hatchery management measures may help mitigate or avoid freshwater bottlenecks or promote returns to preferable spawning habitat through various release strategies. 
 
  2. Assess the likelihood of recovering a self-sustaining wild population, which will inform the enhancement goals, approach, and possible outcomes. For example, where recovery is possible, short-term supplementation can accelerate recovery or stabilize a population while threats/stressors are addressed. Where recovery is unlikely, a hatchery program may be used to satisfy other values, including human and ecosystem use. However, exceptional clarity on the objective of the enhancement would be needed prior to developing these programs, and for Yukon River Chinook salmon, should be limited to small scale low-risk stewardship or assessment objectives. 
 
  3. Design an enhancement plan that is based on spawner recovery goals and corresponding recovery phases and triggers. Rebuilding focused enhancement plans should include defined escapement targets, fisheries reference points, benchmarks that are explicitly tied to wild escapement, and timelines; where hatchery, habitat, and harvest measures are coordinated to meet clearly articulated population, Conservation Unit or stock management goals. 

