# HABITAT {#sec:HABITAT}

## FRESHWATER HABITAT CONDITIONS

The terrain of Yukon includes mountains, plateaus, and valleys that support a diverse mosaic of forest, tundra, grassland, shrubland, and wetland ecosystems. Terrestrial and aquatic ecosystems are considered to be relatively intact across the Yukon watershed [@brabets2000environmental] and access to most of the watershed is limited to boat or aircraft. The Yukon River has considerable seasonable variability in environmental conditions, with summer flows substantially higher than winter flows [@brabets2000environmental]. Streamflows as low as 1,200 $m^3s^{-1}$ occur in the winter, and streamflow discharge pulses of more than 19,800 $m^3s^{-1}$ occur in the spring [@USGS2022]. The river freezes throughout the entire watershed in the winter and ice breakup occurs in late spring, typically by mid-May [@eiler2023swimming]. The mainstem river is relatively deep, greater than 20m in the lower river, but becomes shallower, 8--10m, in the Canadian portion of the drainage [@eiler2023swimming].

The freshwater habitats that Yukon River Chinook salmon utilize are undergoing significant environmental transformations caused by climate change, which are thought to play a role in the decline of their populations [@murdoch2024; @yukon2004ecoregions]. Chinook salmon migrating through the Yukon River basin regularly encounter water temperatures that induce stress responses (above 18$^\circ$C, @usepa2003), particularly in the Porcupine drainage, leading to reduced reproductive success [@murdoch2024; @vonbiela2020]. Over the past several decades, earlier spring melt and river ice breakup have altered migration patterns and habitat availability for aquatic species [@yukon2004ecoregions; @bushlemmen2019]. Thawing permafrost and increased summer precipitation are contributing to higher streamflows and greater sedimentation, and more frequent extreme weather events impact water clarity and quality. These changes are also contributing to unstable riverbanks, further degrading critical spawning and rearing habitats [@murdoch2024]. There is continuous permafrost throughout the Porcupine SMU and part of the Northern Yukon CU [@heginbottom1995canada], and these populations are therefore most likely to experience changes in water quality due to permafrost thawing.

These environmental impacts are expected to intensify under future climate change. More frequent and intense floods due to increased precipitation during the summer months could displace juvenile salmon from their rearing habitats, increasing mortality risks [@murdoch2024]. As glaciers retreat, summer water flows in glacial systems may become less predictable, with potential reductions in water availability during critical salmon migration periods [@yukon2004ecoregions]. Effects of glacial retreat on stream flow and timing have already been seen, notably in Kusawa Lake in southern Yukon (Upper Yukon CU) [@zdanowicz2018] and in Kluane Lake and Slims River (White CU) with the retreat of the Kaskawulsh Glacier [@shugar2017river].

## HABITAT RESTORATION AND MONITORING ACTIVITIES THAT COULD CONTRIBUTE TO REBUILDING

In response to the challenges faced by Chinook salmon across the Canadian portion of the Yukon and Porcupine watersheds, a range of stewardship and restoration activities have been implemented or are being considered. These efforts include watershed and habitat protection, targeted monitoring programs, and cold-water refuge conservation, all aimed at promoting the long-term health and recovery of Yukon River Chinook salmon.

Protecting and restoring creeks and rivers, particularly those vulnerable to increased precipitation and sedimentation, is thought to be important for juvenile salmon survival [@murdoch2024]. Improved environmental monitoring can help to track stream temperatures, flow regimes, and sediment levels to detect early changes in freshwater conditions [@murdoch2024]. Yukon First Nations, Yukon First Nations Salmon Stewardship Alliance, Government of Yukon, and Fisheries and Oceans Canada are working to standardize temperature monitoring throughout the watershed. Sedimentation and high water temperatures frequently occur in areas where the riparian zone is degraded, negatively affecting spawning and rearing habitats [@pusey2003importance]. Restoring riparian zones involves revegetating stream banks and adding large organic debris to stabilize banks and improve habitat quality, which provides shade, regulates water temperature [@kirkland2020; @varner2023], and contributes essential nutrients for salmon. Restoration and reclamation should also include improving floodplain connectivity and lateral stability [@varner2023; @chevrearuxclarkson2015].

Improving fish passage may also support habitat restoration efforts in some portions of the river basin. Barriers like dams and culverts can obstruct salmon migration routes, preventing access to spawning and rearing habitats. Only two significant dams impact the Yukon River Chinook salmon --the Mayo Generating Station completely blocks upstream passage of Chinook salmon of the Stewart CU and the Whitehorse Rapids Generating Station has been shown to have low passage success [@twardek2023adult] for the Upper Yukon CU. Water relicensing processes for the Mayo Generating Station and the Whitehorse Rapids Generating Station are underway, and public comment during both processes have called for installing fish passage [@yukonenergy2024mayo] and improving fish passage, respectively. Such projects should identify and prioritize barriers for remediation, design and implement fish passage solutions such as fish ladders or culvert replacements, and evaluate their success in facilitating salmon movement. Yukon River Drainage Fisheries Association (YRDFA) identified multiple culverts of potential concern for salmon passage, highlighting the need for such assessments [@yrdfa2025springracs] and research has emphasized the need for connectivity between spawning habitats and unobstructed access to them [@brown2017; @isaak2007]. More work with landowners and biologists to idenitify problem culverts in the Canadian portion of the watershed is required. Additionally, there has been increasing scrutiny on beaver dams, which can create passage barriers and reduce connectivity, both for juveniles accessing non-natal streams and for returning spawners [@malison2016; @connors2016course]. Conversely, in some systems there is evidence that ponds created by beaver activity can benefit rearing salmon [@pollock2004importance], and the effect of beaver presence may be highly case-dependent.

Identification and preservation of cold-water refugia are also being considered to protect areas critical to salmon migration and spawning, especially as in-river temperatures rise. Migrating salmon rely on cooler, non-mainstem rivers to reduce stress during these warmer conditions [@eiler2023swimming; @vonbiela2020]. More work is required to locate these refugia. Additionally, identification of groundwater sites used for rearing is critical, as groundwater supplies possibly impact nutrient loads when surface flows are frozen in the winter [@bradford2001]. Identification of juvenile habitat through eDNA or juvenile sampling can help to identify the groundwater locations and habitat to target for regulatory protection. Projects like these, which have already begun primarily in the upper watershed, help identify the habitat use of Yukon River Chinook salmon throughout their life cycle. Increasing the coverage to identify thermal refugia and groundwater throughout the watershed will give a more fulsome picture of productive habitats and contribute to hydrological databases.

Furthermore, water quality is a component of habitat restoration efforts. Pollution, nutrient runoff, and downstream impacts from mining can degrade water quality, affecting salmon health and survival [@gormley2005; @sergeant2022risks]. Identifying sources and levels of pollutants, and understanding their impact on salmon populations, are necessary to inform mitigation strategies. While much of the Yukon River watershed is minimally impacted from land use practices and wastewater management, gold and quartz mining are sources of water contaminants, and legacy mining can have persistent effects for years after remediation [@sergeant2022risks]. In June 2024, a catastrophic failure of the Eagle Gold Mine heap leach pad resulted in a landslide releasing approximately 300 million liters of cyanide laden solution into the surrounding environment. Remediation efforts are ongoing, but elevated levels of cyanide, cobalt, copper, and nitrite have persisted to varying degrees in nearby water bodies, including a tributary of the McQuesten River, a known spawning system in the Northern Yukon CU [@yukongov2025]. The water quality is being closely monitored, but the impacts of the incident on Yukon River Chinook salmon are not yet known. A mining-related spill of 100 million liters of cyanide and heavy metal-laden solution into a tributary of the Tisza River in Romania and Hungary in 2000 caused mass die-offs of many fish species. Following the acute toxicity of the spill, an ecotoxicology study conducted over two years found that while the aquatic community recovered, plants and algae bioaccumulated heavy metals, possibly putting higher tropic levels at risk [@lakatos2003ecotoxicological]. Continued water quality monitoring, particularly in the area of the McQuesten River and in the Klondike River watershed, is critical for determining impacts to salmon from mining. 

There is increasing recognition that a key aspect of any forward-looking restoration is to incorporate Indigenous Knowledge into restoration efforts, as Indigenous communities possess valuable traditional ecological knowledge that can lead or contribute to grounded and impactful conservation strategies. For example, Indigenous Knowledge can provide insights into ecological baselines, such as indicators of salmon abundance (e.g., number of carcasses, smell along riverbanks) or harvest (e.g., reduction in kilograms consumed) which are not captured through conventional monitoring methods [@connoy2024studying; @reid2022learning]. Complementing Indigenous Knowledge with western science confirmed the role of salmon as ecological and cultural keystone species and found that riparian tree growth and nitrogen enrichment was positively related to salmon escapement [@connoy2024studying].

Future efforts may also require changes to regulatory processes to protect salmon habitats. Key recommendations from other works include updating the Fish Habitat Management System for Yukon placer mining to reflect current science, addressing outdated habitat models, and fostering collaboration with Yukon First Nations and industry [@yssc2025]. Additionally, assessing cumulative impacts under key legislation like the Waters Act and modifying the Yukon Environmental and Socio-economic Assessment Act process would allow for stronger salmon conservation measures [@yssc2025]. Removing the free-entry mining system and linking staking rights to development would enable more deliberate decision-making, incorporating environmental reviews and community input [@yssc2025]. These changes aim to strengthen governance and safeguard Yukon's salmon-bearing rivers.

Targeting restoration efforts to those habitats that are hypothesized to be bottlenecks to salmon survival is likely to be the most impactful use of resources. However, some challenges are unlikely to be fully addressed (e.g., those resulting from climate change) except through international or global scale policy. There is growing appreciation for the dynamic nature of salmon habitat and the importance of protecting and preserving the heterogenous and complex habitat landscapes that salmon use and the processes that generate them [@moore2022getting]. 

### CURRENT HABITAT RESTORATION AND MONITORING PROJECTS 

Numerous projects funded through the Yukon River Panel's Restoration and Enhancement Fund are advancing stewardship and habitat restoration efforts across the Yukon River watershed. Additional funding mechanisms and projects are conducted throughout the watershed, though not touched on here. The following paragraphs are just some of the examples of restoration and monitoring occurring. Habitat restoration initiatives such as the Fox Creek stream channel restoration and McIntyre Creek streambank stabilization aim to improve salmon habitat by addressing impacts of beaver dams and streambank erosion [@crawford2023foxcreek]. In-stream incubation of eggs collected from local broodstock has been seen as an alternative to hatchery operations to restore Yukon River Chinook. Multiple year-long in-stream egg incubation projects have been conducted on the traditional territories of Kwanlin Dün First Nation, Teslin Tlingit Council, Tr'ondëk Hwëch'in, Vuntut Gwitchin First Nation, and Ta'an Kwäch'än Council (M. Milligan, pers. comm.) with varying success [@edi2021deadman; @edi2021ibex].   


Monitoring projects underway or recently completed include the Michie Creek Salmon Monitoring Project, which tackles migration barriers for outmigrating Chinook [@jessup2024michie], and the Takhini River Chinook Restoration and Sonar Initiative, which employs drone and sonar technology to monitor Chinook populations [@hoogland2025takhini]. The Beaver River watershed Chinook survey [@mantykapringle2020beaver] focused on understanding Chinook population dynamics to inform conservation strategies while in the Porcupine River the Chinook Salmon Telemetry Project tracked migratory behavior using telemetry [@dfo2017porcupine; @edi2017porcupine]. Tr'ondëk Hwëch'in is monitoring Chinook salmon passage through sonar, and supporting community engagement, youth education, and stewardship through their First Fish initiative [@edi2023klondike; @vittrekwa2023firstfish]. 

These restoration projects also provided promising future directions for ecosystem recovery and stock rebuilding. For instance, drone surveys in the Takhini River will be expanded to identify critical habitats and improve species monitoring. A new sonar site on the Stewart River will assess hydrology, turbidity, and fish passage to support management. In the Klondike watershed, a revised restoration plan could pave the way for small community enhancement efforts. Temperature monitoring will be broadened in key migration corridors such as the Porcupine, Upper Pelly, and White rivers, as well as work to identify cold-water refuges like the Big Salmon and White River tributaries. Planned sonar station upgrades and expanded telemetry studies will boost data reliability, aiding both population tracking and habitat restoration planning efforts. Additionally, targeted habitat enhancement in the face of a changing climate could help to alleviate some of the pressures faced in the freshwater environment. 

