# IMPACT OF FISHERY MANAGEMENT MEASURES {#sec:impact}

## CLOSED LOOP SIMULATION MODEL

We developed a simple closed loop forward simulation, conditioned on our estimates of historical spawner abundance, harvest, age composition, and time-varying productivity (Figure \@ref(fig:fig-schematic)). This model was used to shed light on expected biological and fishery consequences of current and alternative harvest management measures (i.e., Harvest Control Rules [HCRs]) for the Yukon CHinook SMU. The simulation started in the last year for which we had empirical observations (2024) and projected the dynamics of individual CUs forward in time. In each year of the simulation, the model (1) generated a forecast of total returns (with empirically based forecast error), (2) applied a given HCR (see fishery sub-model description below) with outcome uncertainty because management control is not perfect, and (3) allowed remaining fish to spawn and then return in subsequent years across a range of ages at maturity. Details on model components and calculation of performance are provided in the sections below.

### OPERATING MODEL

The operating model was used to simulate future population trajectories for the nine Yukon River Chinook salmon CUs (those in the Yukon Chinook SMU) to which we were able to fit spawner-recruitment models. The operating model projected their population dynamics forward over 26 years (i.e., to 2050, approximately four Chinook salmon generations), thereby generating a distribution of future states conditioned on the historical data. By simulating Yukon Chinook salmon dynamics in this manner, we ensured that predicted future spawner abundance and age structure were conditioned on the incomplete cohorts at the end of the data series (i.e., those cohorts from which one or more older age classes have not yet returned to spawn) and that uncertainties in the spawner-recruit relationships were propagated through time (i.e., by drawing from the joint posterior distributions of each estimated parameter and abundance state in each iteration of the simulation).

Population dynamics were assumed to be driven by @ricker-1954 type spawner ($S$) and recruitment ($R$) relationships:

\begin{equation}
  \ln(R_{i,y}) = \ln(S_{i,y}) + \ln(\alpha_i) - \beta S_{i,y} + v_{i,y}
  \label{eq:AR1-ricker-main}
\end{equation}

where $\alpha$ is productivity (intrinsic rate of growth), $\beta$ is the magnitude of within brood year ($y$) density-dependent effects for CU $i$, and $v_{i,y}$ is lag-1 autocorrelated recruitment residuals (i.e., $v_{i,y}=\phi v_{i,y-1} + \varepsilon_{i,y}$). Correlation in recruitment residuals ($\phi$) was fixed at the average estimate across CUs (0.75) and the portion of recruitment anomalies that is temporally independent, $\varepsilon_{i,y}$, was modeled as a multivariate normal vector:

\begin{equation}
  \varepsilon_{i,y} \sim \mathcal{MVN}\left(\mathbf{0}, \varepsilon_R\right)
  \label{eq:var-covar}
\end{equation}

where the root diagonal of the covariance matrix $\varepsilon_R$ is the CU specific inter-generational variation in survival and where correlation in the recruitment residual time series vectors $\boldsymbol{\varepsilon}_i$ and $\boldsymbol{\varepsilon}_k$ between CU $i$ and $k$ ($\rho_{i,k}$) is captured in the off-diagonal covariance elements of $\varepsilon_R$. This variance-covariance matrix was fixed at the median estimates of the variance-covariance matrix of recruitment residuals by CU and year as estimated in the spawner-recruitment model described in Appendix \@ref(app:third-appendix).

Returns in calendar year $t$, $N_{t,i}$, were then modeled as a function of the proportion of individuals that mature and return at each age:

\begin{equation}
  N_{t,i} = \sum_{a=4}^{7} R_{(t-a)} p_{(a-3)}
  \label{eq:totalreturn-main}
\end{equation}


where $p$ is the maturity schedule composed of four age classes (ages four through seven). In each year of the forward simulation, the number of spawners in Equ. \@ref(eq:AR1-ricker-main) was calculated as the total return (Equ. \@ref(eq:totalreturn-main)) minus aggregate harvest which was determined according to the harvest control rules described in the following section.

In each iteration of the forward simulation (n = 1000) the operating model was parameterized by taking a draw from the joint posterior distributions of the relevant parameters from the spawner-recruitment models with time-varying intrinsic productivity fit to each CU (Equ. \@ref(eq:AR1-ricker)-\@ref(eq:tv-alpha)). A summary of the parameters is provided in Tables \@ref(tab:tab-ref-sim-params) and \@ref(tab:OM-scenarios).In our reference (base) scenario, we projected system dynamics forward using the average $\alpha$ estimates of the six most recent completely observed brood years (2013--2018), which corresponds with the 6-year generation length for Yukon River Chinook salmon (Figure \@ref(fig:fig-prod-scenarios)). As a robustness (alternative or "worst case") scenario we also projected the system forward in time assuming intrinsic productivity was instead equal to the last empirical estimate of time varying productivity (i.e., 2017 brood year) which serves as a test of the consequences of alternative harvest management measures if productivity were to remain severely depressed for the next several generations (~35% on average lower than most recent generation average; Figure \@ref(fig:fig-prod-scenarios)). We also considered another robustness ("best case") scenario where the system was projected forward using the median $\alpha$ estimates from all fully observed brood years (1985--2017), which illustrates the outcomes if the stock were to return to long term average productivity (Figure \@ref(fig:fig-prod-scenarios), Table \@ref(tab:OM-scenarios)). It is possible that productivities in future years may also become more variable (e.g., due to climate induced extreme events) but for simplicity such scenarios were not considered.

For simplicity we chose to not explicitly model spawner demographics and the consequences of changing demographic characteristics. We chose to do this because we consider our demographic spawner recruitment models to be exploratory/illustrative (described in more detail in Appendix \@ref(app:third-appendix)) and because by conditioning our operating model on recent productivity we are in effect implicitly accounting for the cumulative consequences of both demographic and environmental/ecosystem change on the intrinsic productivity of each CU.

### FISHERY SUB-MODEL

In each year of the simulation, total returns were assumed to be forecasted with error. This error was assumed to be lognormally distributed with a mean equal to the true run size and a standard deviation of 0.79, based on a retrospective assessment of the mid-point of preseason forecasts and true run size 2000-present [@JTC2025Report]. Forecasted returns were then used as an input into a given HCR that specified a target exploitation rate given the expected run-size. Outcome uncertainty (i.e., deviations from targeted catch due to imperfect management control) was then applied to calculate realized catch, where outcome uncertainty was assumed to be equal to a CV of 10% which is of a magnitude similar to that assumed in other large Chinook salmon fisheries in the region [@connors2022]. We do not simulate in-season management or forecast adjustments, therefore our simulations likely over-estimate the true magnitude of combined forecast and management error.

The harvest control rules (HCRs) we considered are shown in Figure \@ref(fig:fig-hcrs) and described in Table \@ref(tab:hcrs). These alternative fishery management measures ranged from a no fishing scenario to illustrate expected recovery potential, to fixed exploitation rate rules intended to simply illustrate the expected impact of a range of harvest rates, to escapement goal type rules (with and without caps on maximum exploitation) that were intended to approximate a range of general harvest management strategies. For the latter general harvest management strategies it was assumed that the current 7-year agreement ("moratorium") rule was in effect until 2030, after which the given HCR being simulation tested took effect. 

With the exception of the fixed exploitation rates, harvest control rules were defined by a a lower management reference point and in some cases an upper reference point and/or maximum removal reference, all defined at the SMU scale. When there was both a lower and upper reference point, harvest rates linearly increased from zero at spawner abundances below the lower reference point to the maximum removal reference at run sizes equal to the spawner abundances associated with the upper reference point. The maximum removal rate was never allowed to exceed 80% under any HCRs because this is the maximum estimated aggregate harvest rate to have been experienced by the stock (in 1987) and for those HCRs with a cap on the maximum allowable exploitation rate it was set to 36% which was the the median estimate of $U_{MSY}$ for the least productive CU (Section \@ref(sec:smu-rps)). Conservation Units were assumed to be equally vulnerable to harvest, and low levels of incidental harvest (~1000 fish) were assumed to occur even in years where the HCR being applied would call for a fishery closure to account for mortality due to assessment projects and unregulated harvest.

### PERFORMANCE MEASURES

We quantified the expected performance of current and alternative harvest management measures against biological and fishery objectives and associated performance measures (Table \@ref(tab:tab-perf-metrics-descriptions)). We considered the primary biological objectives to be minimizing the number of CUs below their lower biological benchmarks, and maximizing the number of CUs above their upper biological benchmarks. We derived these benchmarks from the spawner-recruitment models that assumed time-invariant productivity (Appendix \@ref(app:third-appendix)) and note that simply reporting the number of CUs that fall above their lower biological benchmarks may underestimate extinction risk which is more explicitly accounted for in the formal Wild Salmon Policy rapid status assessments. We also calculated the number of CUs above their rebuilding target, which was (100%) $S_{MSR}$ based on egg mass recruitment models with time-invariant productivity where $S_{MSR}$ is based on demographic characteristics of spawners over the most recent generation of data (2019-2024). In addition to these CU scale status performance measures, we also calculated average annual aggregate spawner abundance.

Fishery related performance measures included realized total aggregate harvest, realized aggregate harvest rate, the proportion of years when the fishery closed, and average annual total harvest occurring in Canada. Under the harvest sharing provisions of the Yukon River Salmon Agreement [@agreement2001], 20%--26% of total allowable catch is allocated to Canada when projected Total Allowable Catch is less than 110,000, which we simplified to a target of 23% in order to calculate the total Canadian harvest. 

## CONSEQUENCES OF CURRENT AND ALTERNATIVE HARVEST MANAGEMENT MEASURES

Under the reference productivity scenario and no fishing, median spawner abundances were projected to be at or below lower biological benchmarks from 2030--2050 for three CUs: Northern Yukon, White, and Pelly. Two CUs (Middle Yukon and Big Salmon) were projected to be between lower and upper benchmarks, and two (Stewart and Upper Yukon) were above their upper benchmarks and lastly, the Nordenskiold and Teslin CUs were projected to approach or exceed their CU-specific rebuilding targets (Figure \@ref(fig:fig-projections)).

Simulations across a range of fixed harvest rates highlighted a clear tradeoff between mixed-stock fishery harvests and risks to component CUs. Aggregate harvests were projected to be maximized at mixed-stock harvest rates of \~60%, and dominated by harvest from the Middle Yukon and Nordenskiold CUs, but at this harvest rate at least four CUs were projected to be extinct and another three below their lower biological benchmark and hence at an elevated risk of extinction (Figure \@ref(fig:fig-ER-tradeoff-ref)).

The current moratorium on fishing at run-sizes below 71,000 allowed for populations to be stable and modest opportunities for harvest in the forward projections under the reference productivity scenario (Figure \@ref(fig:fig-projections)). Specifically, annual exploitation rates averaged 10%, and total harvest was projected to be \~3,000 fish on average per year, though this was variable from year to year. Notably, this harvest control rule resulted in the fishery being closed to harvest in \~80% of years between 2030--2050. Harvest in Canada averaged \~600 fish per year, which is well below Yukon First Nations Basic Needs Allocation for Chinook salmon which, while not finalized, is the interim allocation of Chinook salmon (10,000 fish) reserved for Yukon First Nations within the current Canadian fishery management strategy [@dfo2024yukonifmp]. Under this harvest control rule median spawner abundances were projected to exceed CU specific lower biological benchmarks for six CUs, and exceed upper biological benchmarks for four of those six. Placing a maximum harvest rate cap equal to the removal reference (RR) on this harvest control rule very slightly reduced average annual harvest rates and harvest but otherwise had little impact on the biological performance measures.

The interim management escapement goal (IMEG) harvest control rule of 42,500 resulted in the highest average harvest rates (\~16%) and harvest (\~5,000), and lowest aggregate spawner abundance (\~25,000), of the alternative fishery management measures considered. These higher harvests resulted in the highest number of CUs falling below their lower biological benchmarks. Under this scenario \~70% of years were expected to have complete fishery closures. Placing a maximum harvest rate cap on the IMEG harvest control rule reduced the average harvest rate to \~14% and reduced the chances of any CUs falling below their lower biological benchmarks. Lastly, the Precautionary Approach alternative, which allowed harvest at lower abundances than the other harvest control rules, had similar biological performance to the moratorium scenarios, but reduced the frequency of fishery closures from four in five years (80%) to approximately one in four (25%, Figure \@ref(fig:fig-perf-ref), Table \@ref(tab:tab-ref-perf-measures)).

Under the robustness scenario where intrinsic productivity was assumed to remain severely depressed for the next several generations, all harvest control rules resulted in very limited opportunities for harvest and resulted in over half of CUs being extinct or at risk of extinction (Table \@ref(tab:tab-rob-perf-measures)). While relative fishery performance varied slightly among HCRs similarly to under the reference scenario, absolute fishery performance was low in all cases under the depressed productivity scenario.

Under the second robustness scenario where productivity was assumed to return immediately to its long-term average, all harvest control rules resulted in more positive fishery and biological outcomes. Under the IMEG rule, one CU was at risk of falling below its lower benchmark, but placing a cap on the maximum allowable harvest rate removed this risk (Table \@ref(tab:tab-rob2-perf-measures)). Notably, this was the only harvest control rule and productivity scenario under which a Basic Needs Allocation for Yukon First Nations was consistently met, assuming that Yukon First Nations got priority access to Canadian harvest.
