# DISCUSSION     {#sec:discussion}

## SUMMARY OF KEY FINDINGS 
In this report we describe Yukon Chinook salmon stock structure and distribution, stock assessment history, and analyses that combine genetic stock identification of archived scale and tissue samples with run-reconstruction models to estimate migration timing and annual return abundance for nine Conservation Units (CUs) of the Yukon Chinook SMU. We then characterize CU scale population dynamics of the Yukon Chinook SMU and estimated biological reference points by fitting age-structured, state-space spawner (or egg mass) recruitment models to observations of spawner abundances, harvest, and age composition. Anthropogenic, ecosystem, and climate factors affecting both the Porcupine and Yukon Chinook SMUs are described along with general rebuilding and enhancement activities that could contribute to growth of the SMUs. Lastly, quantitative estimates of the expected biological and fishery consequences of current and alternative harvest management measures are generated from a closed loop simulation model for the Yukon Chinook SMU.

Aggregate returns of Yukon Chinook salmon have declined in recent decades culminating in five of the lowest returns on record in 2020--2024. These declines have placed immense hardship on subsistence users and Yukon First Nations who depend on Chinook salmon for food, social and cultural uses, and prompted a seven-year moratorium on directed harvest in Alaska and Canada beginning in 2024. Declines in female Chinook salmon age at maturity, and to a lesser extent the proportion of females in the spawning population, have resulted in a marked decline in average reproductive output per spawner (~25% from the late 1980s to the early 2020s). Concurrent with these changes intrinsic productivity has declined by an average of 60% across CUs.

Reconstructed spawner abundances at the CU scale for the Yukon Chinook SMU were on average 42% lower in the most recent generation (2018--2024) than preceding generations (1985--2017). Three CUs (Nordenskiold, Upper Yukon, Stewart, and White) were assessed as in the Wild Salmon Policy Red status zone due to their spawner abundances being below an absolute abundance lower threshold of 1,500 spawners. The Northern Yukon CU was assessed as in the Red status zone because spawner abundances over the most recent generation were below its lower biological benchmark, and the Teslin and headwaters CU was assessed as in the Red status zone based on trends in spawner abundance from two long-running aerial surveys. Two additional CUs, the Porcupine and Old Crow, were assessed as in the Red status zone due to their combined average abundance over the most recent generation being 695. The remaining CUs were assessed as in the Amber status zone, though with low confidence due to potential unaccounted migration mortality and uncertainties in how well spawner abundances could be reconstructed. 

At the SMU scale, Chinook salmon run-sizes declined by ~87% from 1981-2024. Because multiple CUs were assessed as falling in the Red status zone, the Yukon Chinook SMU is below its CU status based Limit Reference Point. Aggregate spawner abundances over the most recent generation (2019--2024) averaged 25,852 which is slightly above the proposed  lower fishery reference point of 19,000 and well below the proposed Upper Stock Reference point of 95,000 (Section \@ref(sec:smu-rps)). Realized harvest rates over this same time period averaged 16%. The Porcupine Chinook salmon SMU is also below its CU status based LRP because two CUs were assessed as being in the Wild Salmon Policy Red zone. 

The past decade has seen a considerable amount of research into anthropogenic, ecosystem, and climate factors that may have contributed to the recent and long-term declines in body size and productivity of Yukon Chinook salmon. Leading hypotheses for drivers of these changes include heat stress and *Ichthyophonus* infection during return migrations, and climate induced changes to predator, prey and competitor abundances in the Bering Sea ecosystem that Yukon Chinook salmon spend much of their marine life in. Several enhancement activities have been directed towards Yukon Chinook salmon over the past 40 years including hatcheries, incubation facilities, and in-stream incubation projects. These enhancement projects have been modest in nature and while there is general agreement that enhancement may support rebuilding efforts, more research and work is needed to determine where enhancement could be effective and how to minimize the potential for adverse impacts. A range of stewardship and restoration activities have been implemented or considered for Yukon Chinook salmon. These efforts include watershed and habitat protection through specific changes in regulations, targeted monitoring programs, and cold-water refuge conservation, all aimed at promoting the long-term health and recovery of Chinook salmon returning to the Canadian portion of the Yukon River basin.

Simulations on the Yukon Chinook SMU suggest that the current moratorium on fishing at aggregate run sizes less than 71,000 allows for some stock growth and hence future harvest opportunities over the next 26 years. Spawner abundances are projected to exceed CU-specific lower reference points for all CUs by the end of this time period, and three CUs are projected to exceed their upper reference points, provided that productivity remains at its 10-year average. Under this scenario harvest is projected to be ~10,000 fish on average per year (2030--2050) though this is highly variable from year to year and only 30% of years are expected to result in First Nations Basic Needs Allocation being met (assuming they were given priority access to any harvest opportunities). Evaluation of the interim management escapement goal in place prior to the 2024 moratorium suggests that it can achieve higher average harvests but at the cost of one CU projected to fall below its lower biological reference point and only two CUs projected to be above their upper biological reference point. Lastly, a Precautionary Approach compliant Harvest Control Rule (HCR), which allowed harvest at lower abundances than the other HCRs, had similar biological performance and chances of meeting Basic Needs Allocation as the moratorium HCR, but reduced the frequency of fishery closures from one in every two years to one in every ten. These simulations assumed the intrinsic productivity of the CUs that make up the Yukon Chinook SMU is depressed but remains the same as it has been over the last decade moving forward. Under an alternative worst-case scenario where productivity is assumed to be severely depressed (60% below most recent decade average) all alternative harvest management measures considered resulted in very limited opportunities for harvest, and up to four CUs were projected to fall below their lower biological reference points by 2050.

## EXCEPTIONAL CIRCUMSTANCES OR ASSESSMENT TRIGGERS FOR THE STOCK 
Exceptional circumstances are assessment triggers intended to proactively identify conditions and/or circumstances that may represent a substantial departure from those under which the advice in this assessment was developed. 

In addition to routine re-assessment every generation to ensure stock status can be updated and captures contemporary fishery and biological processes, we recommend a re-assessment be triggered if any of the following occur:

- Stock productivity changes drastically, where the median estimate of time-varying productivity (annual CU-specific Ricker $\alpha$) falls outside the 50th percentiles of the productivity used to condition our forward simulation under the robustness test (most recent $\alpha$);

- Management measures other than those evaluated in this research document are considered by fisheries management;  

- New information becomes available that results in changes to our understanding of stock-structure (e.g., the current Conservation Unit delineations) and/or major drivers of stock dynamics; or 

- New information becomes available that results in changes to the historical time-series of spawner abundance and/or catches used in this research document (e.g., historical estimates of migration mortality are derived and incorporated into the run-reconstructions).

## KEY KNOWLEDGE GAPS AND AREAS OF POTENTIAL FUTURE WORK  
As is inevitable with any analyses of large and complex ecological and fishery datasets, we had to make a number of simplifying assumptions. These include: 

1. **Assuming all Conservation Units have historically been equally vulnerable to fisheries**. Our reconstructions of CU scale harvests, and subsequent population dynamics modelling and estimation of reference points, relied on reconstructed estimates of Canadian-origin Yukon Chinook salmon harvest rates [@connors_estimates_2023] which were then used to calculate CU-specific harvest based on reconstructed spawner abundance. This approach implicitly assumes that all CUs have historically experienced the same harvest rates. We consider this a reasonable assumption because Canadian-origin Chinook salmon make up the first “pulse” of Chinook salmon to enter the Yukon River each year and subsistence and commercial fisheries (e.g., openings and closures and gear restrictions) have historically been managed by pulse. And for those few years where genetic sampling of harvest in Alaska allowed for a comparison of CU composition in both border passage and harvest there was no evidence of consistent over/under-representation of individual CUs in Alaskan harvest (Appendix \@ref(app:sixth-appendix), Figure \@ref(fig:fig-CU_harv-compare). Nonetheless, it is possible that differences in run timing, and the timing of fisheries during the first pulse in the lower river in Alaska, have led to earlier returning fish being more vulnerable to harvest than later returning fish. This has the potential to underestimate harvest rates for populations that return relatively early and overestimate harvest rates for those that return relatively late (e.g., Northern Yukon and White CUs) which in turn may under- and over-estimate productivity, respectively. However, the actual timing of lower river harvests has varied over time and is difficult to separate from the harvest of co-migrating Chinook salmon that spawn in the middle and lower portions of the Yukon River Basin. Thus, it may not be possible to accurately reconstruct the timing and magnitude of the gauntlet of commercial and subsistence fisheries that historically occurred and that Canadian-origin Yukon River Chinook salmon would have experienced along the length of the Yukon River.

2. **Assuming there has been no en-route adult migration mortality from the U.S.--Canada border to spawning grounds**. Our reconstructions of CU scale spawner abundances assumed that the only source of mortality after passing the border was harvest. However, elevated water temperatures and *Ichthyophonus hoferi* disease have been identified as two relatively common stressors that may result in premature mortality of Yukon Chinook salmon throughout the U.S. or Canadian portions of the drainage during their adult spawning migrations [@vonbiela2020; @biela2022premature; @connors_estimates_2023; @howard2023]. Historical tagging studies of return adult Chinook salmon have found that years when freshwater migration conditions were relatively cool and relatively warm had comparable movements and survival rates [@eiler2023swimming]. However, more recent tagging studies, undertaken as a collaboration between ADFG, DFO, and Yukon First Nations, and during a period of higher migration temperatures than in previous studies, suggest that not all tagged fish make it to their spawning grounds. However, this work is ongoing and at present the magnitude of en-route adult migration mortality exhibited by Yukon Chinook salmon on an annual basis is not known, but likely varies substantially in space and over time. Failing to account for en-route adult migration mortality in our CU run-reconstructions would result in overestimates of spawner abundance in years in which it occurs, and potential for biologically optimistic estimates of CU status. For this reason, assessment of biological status for headwater CUs were deemed to be of lower confidence if they relied on border passage reconstructions instead of assessments on or closer to spawning grounds. 

3. **Assuming Conservation Unit age composition can be approximated by Canadian-origin stock aggregate age composition**. Our CU scale spawner recruitment analyses assumed all CUs shared a common age-at-return that varied through time. While there is undoubtedly some among-CU variation in age-at-return, this assumption was a necessary simplification due to the availability of age composition information at the CU level. Age composition data from fish sampled at the U.S.--Canada border can be assigned to individual CUs from ~2005 to present, but our ability to link genetic and age information for samples prior to 2005 was limited, and tributary scale age composition is very patchy. For those years where we can compare CU-specific and aggregate age composition, there is not strong evidence of differences among the estimated age compositions (Appendix \@ref(app:sixth-appendix); Figures \@ref(fig:fig-age-compare) and \@ref(fig:fig-blind-age-compare)), but it is possible that relatively subtle among-CU differences in age composition could bias our estimates of recruitment (the sum of all fish that returned for a given spawning cohort). This could in turn influence our inference about the shape of the spawner-recruitment relationship and resulting estimates of population productivity and abundance [@zabel2002simple] though these impacts may be relatively small [@peacock2020evaluating].

4. **Assuming future productivity will remain similar to that observed over the past decade**. Our closed-loop simulation evaluation of alternative fishery management measures required us to make assumptions about what CU-scale intrinsic productivity was likely to be over the course of the simulations. There is clear evidence of interannual variation and declines in intrinsic productivity over time, so we assumed that estimates of the last decade of CU-specific productivity were a reasonable proxy for the coming decades. We also considered an alternative scenario where productivity is assumed to remain severely depressed (60% below most recent decade average) moving forward. Assumptions about intrinsic productivity will impact projection of recovery potential and fishery outcomes, and while both productivity scenarios we considered were based on empirical observations, it is possible that productivity continues to decline further. 

There are several areas of assessment and research that warrant attention moving forward. Doing so can help to resolve key uncertainties and improve the scientific basis upon which management decisions are made. These include, but are not limited to:

- **Increased/continued tributary scale assessment effort**. While the analytical work detailed in this report represents our best efforts to shed light on CU scale dynamics and status based on the patchwork of available information, quantitative models that attempt to reconstruct dynamics from limited data are no substitute for long-term investment in spawning ground assessments at the tributary and/or CU scale. All CUs currently have tributary scale assessments projects in operation with the exception of the Stewart (Table \@ref(tab:assess-proponents)) and estimates of spawner abundances from these projects tend to correlate fairly well with the CU scale run reconstructions (Figure \@ref(fig:fig-trib-vs-CU-spawn)). Continued investment to ensure these assessment projects remain in operation, and consideration of opportunities to develop assessment(s) in the Stewart CU, will help ensure that empirical estimates of spawner abundance are available to compliment the run-reconstructions and assess CU status moving forward. In addition, futher development of the CU scale run-reconstruction models could consider attempting to fit to the tributary indices of abundance where possible.   

- **Improved assessments, run reconstructions, and reference points for the Porcupine Stock Management Unit**. The Porcupine Chinook SMU is largely data limited. Sonar assessments for two of three CUs (Old Crow and Porcupine) began in 2014, but there is no assessment of the Salmon Fork CU. Improved assessment and continued monitoring of Chinook salmon in the mainstem Porcupine River would help to produce run reconstructions and reference points for two of the CUs. The Salmon Fork River breaks off from the mainstem Porcupine River near Old Rampart, Alaska, and due to the remoteness of the location, there are no assessment projects for this portion of the watershed. Beginning assessments for the Salmon Fork River, or developing a radio-tagging project to identify the spawning locations of the Chinook salmon in the Salmon Fork River, would help to address knowledge gaps in the Porcupine SMU. 

- **Improved understanding of en-route migration mortality and its implications for CU assessment and evaluations of fishery management measures**. Given that the magnitude of en-route adult migration mortality exhibited by Yukon Chinook salmon on an annual basis is not known, but likely varies substantially in space and over time, continued investment in telemetry assessment projects, and research into correlates of potential migration mortality back through time, will enable future evaluation of the consequences of accounting for this mortality on CU assessment and forward looking evaluations of fishery management measures. This work could include exploration of the use of tributary indices of spawner abundance as an additional source of data the multi-CU reconstruction model is fit to and potential to directly estimate migration mortality (e.g., as informed by the difference between border passage and spawning ground reconstructed abundance).

- **Climate and ecosystem informed life cycle modelling**. Assessments of juvenile Yukon Chinook salmon abundances in the Bering Sea have occurred for the past several decades. Fish sampled in these surveys have been assigned to Canadian, middle Yukon, and lower Yukon stock groups based on genetics, but  consideration should be given to whether they could be assigned (historically and/or moving forward) to CUs in a manner similar to what we have detailed for adults sampled at the U.S.--Canada border. At either scale, these juvenile data can be used to inform life cycle models that could explicitly incorporate and update those ecosystem and environmental conditions that have previously been shown to correlate with Yukon Chinook salmon productivity [@cunningham2018; @murdoch2024; @feddern2024]. When coupled with future projections of climate and ecosystem change, such analyses may help shed light on future recovery potential and impacts of alternative management measures. 

- **Revisiting Conservation Unit delineations and measures of genetic diversity**. The current CU delineations are based on a genetics baseline and analyses that are over a decade old [@holtbyConservationUnitsPacific2007; @holtby2011]. These delineations should be revisited based on the updated genetics baseline collection, and updated evaluations of genetic evidence for population structure along with traditional and local ecological knowledge. 
